package com.aiqaos.brain.manager;

import com.aiqaos.core.contract.BrainRequest;
import com.aiqaos.core.contract.BrainResponse;
import com.aiqaos.core.engine.QABrainEngine;
import org.springframework.stereotype.Service;

@Service
public class BrainManagerImpl implements QABrainEngine {

    @Override
    public BrainResponse processBrainDecision(BrainRequest request) {
        BrainResponse response = new BrainResponse();
        response.getMetadata().setCorrelationId(request.getMetadata().getCorrelationId());
        response.getMetadata().setTraceId(request.getMetadata().getTraceId());
        response.setPlanSummary("Mock QA Plan generated by QA Brain");
        response.setStatus("SUCCESS");
        return response;
    }
}