spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

aiqaos:
  application:
    environment: test
  security:
    enabled: false
  features:
      realtime-logging: false

security:
  jwt:
    secret: 9a7263b65e94b29c9ef63d274bfd4e1d73504ad09bca3b22e11d2e16f3918a5f
    expirationMs: 3600000
    refreshExpirationMs: 86400000
    issuer: ai-qa-os-auth-service