spring:
  profiles:
    active: local
  application:
    name: ai-qa-os

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always