package com.aiqaos.core.enums;

public enum AgentType {
    PLANNING,
    QA_ENGINEER,
    VALIDATOR,
    CODER,
    REPORTER,
    SUPERVISOR,
    TEST_CASE_GENERATOR,
    SCRIPT_GENERATOR,
    EXECUTION_ENGINEER,
    BUG_ANALYZER,
    LEARNING_ENGINEER,
    SELF_HEALING_ENGINEER
}