package com.aiqaos.observability.metrics;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.concurrent.atomic.AtomicLong;

/**
 * OBS-2: PipelineMetricsRecorder — records real Micrometer metrics for the
 * AI-QA-OS autonomous pipeline, scraped by Prometheus at /actuator/prometheus.
 *
 * Metric catalogue:
 *  qaos_pipeline_runs_total{status}   — Counter: completed pipeline runs by status
 *  qaos_pipeline_duration_seconds     — Timer:   full pipeline execution duration
 *  qaos_pipeline_steps_total{step,status} — Counter: individual step completions
 *  qaos_llm_calls_total{model,status} — Counter: LLM API calls (hit=cache, ok=live, err=error)
 *  qaos_llm_tokens_total{model,type}  — Counter: token usage (prompt/completion)
 *  qaos_active_pipelines              — Gauge:   currently running pipelines
 *  qaos_healing_attempts_total{outcome} — Counter: self-healing attempts by outcome
 *  qaos_test_cases_generated_total    — Counter: test cases generated by the AI
 */
@Component
public class PipelineMetricsRecorder {

    private static final Logger log = LoggerFactory.getLogger(PipelineMetricsRecorder.class);

    private final MeterRegistry registry;

    // Gauge backing — AtomicLong so the Gauge lambda can read a consistent snapshot
    private final AtomicLong activePipelines = new AtomicLong(0);

    // Pre-registered frequently-hit counters for zero-allocation hot path
    private final Counter pipelineSuccessCounter;
    private final Counter pipelineFailedCounter;
    private final Counter testCasesGeneratedCounter;

    public PipelineMetricsRecorder(MeterRegistry registry) {
        this.registry = registry;

        // OBS-2: active pipeline Gauge — Prometheus will poll this on every scrape
        Gauge.builder("qaos_active_pipelines", activePipelines, AtomicLong::get)
                .description("Number of pipeline runs currently in progress")
                .register(registry);

        this.pipelineSuccessCounter = Counter.builder("qaos_pipeline_runs_total")
                .tag("status", "success")
                .description("Total completed pipeline runs")
                .register(registry);

        this.pipelineFailedCounter = Counter.builder("qaos_pipeline_runs_total")
                .tag("status", "failed")
                .description("Total completed pipeline runs")
                .register(registry);

        this.testCasesGeneratedCounter = Counter.builder("qaos_test_cases_generated_total")
                .description("Total test cases generated by the AI pipeline")
                .register(registry);

        log.info("OBS-2: PipelineMetricsRecorder registered with Micrometer (Prometheus-ready)");
    }

    // ─── Pipeline lifecycle ────────────────────────────────────────────────

    /** Call when a pipeline run starts. Increments the active gauge. */
    public void pipelineStarted() {
        activePipelines.incrementAndGet();
    }

    /** Call when a pipeline run completes. Records duration and status counter. */
    public void pipelineCompleted(String status, long durationMs) {
        activePipelines.decrementAndGet();
        if ("success".equalsIgnoreCase(status)) {
            pipelineSuccessCounter.increment();
        } else {
            pipelineFailedCounter.increment();
        }
        Timer.builder("qaos_pipeline_duration_seconds")
                .tag("status", status)
                .description("Pipeline end-to-end execution duration")
                .register(registry)
                .record(java.time.Duration.ofMillis(durationMs));
        log.debug("OBS-2: pipeline completed status={} duration={}ms", status, durationMs);
    }

    // ─── Step metrics ──────────────────────────────────────────────────────

    /** Records the outcome of a single named workflow step. */
    public void stepCompleted(String stepName, String status, long durationMs) {
        Counter.builder("qaos_pipeline_steps_total")
                .tag("step", stepName)
                .tag("status", status)
                .description("Individual workflow step completions")
                .register(registry)
                .increment();
        Timer.builder("qaos_step_duration_seconds")
                .tag("step", stepName)
                .tag("status", status)
                .description("Workflow step execution duration")
                .register(registry)
                .record(java.time.Duration.ofMillis(durationMs));
    }

    // ─── LLM metrics ──────────────────────────────────────────────────────

    /**
     * Records an LLM API call.
     *
     * @param model  e.g. "gemini-1.5-pro"
     * @param status "ok" | "cached" | "error"
     * @param promptTokens   tokens sent to the model
     * @param completionTokens tokens received from the model
     */
    public void llmCallRecorded(String model, String status, int promptTokens, int completionTokens) {
        Counter.builder("qaos_llm_calls_total")
                .tag("model", model)
                .tag("status", status)
                .description("LLM API calls by model and status (ok/cached/error)")
                .register(registry)
                .increment();

        Counter.builder("qaos_llm_tokens_total")
                .tag("model", model)
                .tag("type", "prompt")
                .description("Total LLM tokens consumed")
                .register(registry)
                .increment(promptTokens);

        Counter.builder("qaos_llm_tokens_total")
                .tag("model", model)
                .tag("type", "completion")
                .description("Total LLM tokens consumed")
                .register(registry)
                .increment(completionTokens);
    }

    // ─── Self-healing metrics ───────────────────────────────────────────────

    /** Records a self-healing attempt (locator repair, retry, etc.). */
    public void healingAttemptRecorded(String outcome) {
        Counter.builder("qaos_healing_attempts_total")
                .tag("outcome", outcome)   // "healed" | "failed" | "skipped"
                .description("Self-healing attempts by outcome")
                .register(registry)
                .increment();
    }

    // ─── Test generation metrics ────────────────────────────────────────────

    /** Records N test cases generated in a pipeline run. */
    public void testCasesGenerated(int count) {
        testCasesGeneratedCounter.increment(count);
    }
}
